### ISSUE TITLE
Thank you very much for your work. While running your code, I encountered some problems. May I know how to solve them?

### ISSUE THREAD

**Issue by scotchaer** [nivha/single_video_generation#2]
`(vgpnn) C:\ai\single_video_generation-main>python run_generation.py --gpu 0 --frames_dir data/airballoons_QGAMTlI6XxY --start_frame 66 --end_frame 80 --max_size 360 --use_noise False --min_size '(6,40)'
Namespace(J=5, J_start_from=1, downfactor=(0.85, 0.85), end_frame=80, frames_dir='data/airballoons_QGAMTlI6XxY', gpu='0', kernel_size=(3, 7, 7), max_size=360, min_size='(6,40)', noise_amp=5, reduce='median', results_dir='./results/generation', save_intermediate=True, save_intermediate_path='./results/generation', start_frame=66, sthw=(0.5, 1, 1), use_noise=False, verbose=True, vgpnn_type='pm')
Traceback (most recent call last):
  File "run_generation.py", line 70, in <module>
    VGPNN, orig_vid = vgpnn.get_vgpnn(
  File "C:\ai\single_video_generation-main\vgpnn.py", line 217, in get_vgpnn
    downscales, upscale_factors, out_shapes = scale_utils.get_scales_out_shapes(T, H, W, o.downfactor, o.min_size)
  File "C:\ai\single_video_generation-main\utils\scale_utils.py", line 48, in get_scales_out_shapes
    assert T >= min_size[0], f"min_size ({min_size[0]},{min_size[1]}) larger than original size ({T},{H},{W}) (it must be smaller)"
TypeError: '>=' not supported between instances of 'int' and 'str'

(vgpnn) C:\ai\single_video_generation-main>python run_generation.py --gpu 0 --frames_dir data/airballoons_QGAMTlI6XxY --start_frame 6 --end_frame 80 --use_noise False
Namespace(J=5, J_start_from=1, downfactor=(0.85, 0.85), end_frame=80, frames_dir='data/airballoons_QGAMTlI6XxY', gpu='0', kernel_size=(3, 7, 7), max_size=144, min_size=(3, 15), noise_amp=5, reduce='median', results_dir='./results/generation', save_intermediate=True, save_intermediate_path='./results/generation', start_frame=6, sthw=(0.5, 1, 1), use_noise=False, verbose=True, vgpnn_type='pm')
Traceback (most recent call last):
  File "run_generation.py", line 70, in <module>
    VGPNN, orig_vid = vgpnn.get_vgpnn(
  File "C:\ai\single_video_generation-main\vgpnn.py", line 226, in get_vgpnn
    assert ret_pyr[0].shape[2] >= o.kernel_size[0], f'smallest pyramid level has less frames {ret_pyr[0].shape[2]} than temporal kernel-size {o.kernel_size[0]}. You may want to increase min_size of the temporal dimension'
AssertionError: smallest pyramid level has less frames 2 than temporal kernel-size 3. You may want to increase min_size of the temporal dimension`

**Comment by nivha** [comment]
Hi @scotchaer ,

I'm sorry for the late reply but I no longer really maintains this repo. This bug happens because at the coarsest level of the pyramid, the number of channels is smaller than the kernel-size for the temporal dimension (and therefore the rest of the algorithm cannot operate on this). That's why I put this error message there..

The bug is that the "min_size" is not strictrly enforced in this case (if I remember correctly). This can be "fixed" by changing the downfactor or the input shape, so that in the coarsest scale, the temporal dimension won't end up being too small (i.e., number of channels smaller than kernel size). 
Ideally, you could maybe add code to automatically "fix" the downfactor so the coarsest level would have the required min_size, or something along this line. 

As I said, I'm no longer maintaining this repo, but if you (or someone else in the future) are willing to make a pull request I will gladly approve it.

All the best, Niv
