### ISSUE TITLE
run_generation.py stops with an error

### ISSUE THREAD

**Issue by Frank-Buss** [nivha/single_video_generation#3]
When I run it on the ballet example like this:
```
python3 run_generation.py --frames_dir=/home/frank/tmp/ballet/ballet_Wz_f9B4pPtg --start_frame=1 --end_frame=60
```
Then I get this error:
```
Namespace(gpu='0', results_dir='./results/generation', frames_dir='/home/frank/tmp/ballet/ballet_Wz_f9B4pPtg', start_frame=1, end_frame=60, max_size=144, min_size=(3, 15), downfactor=(0.85, 0.85), J=5, J_start_from=1, kernel_size=(3, 7, 7), sthw=(0.5, 1, 1), reduce='median', vgpnn_type='pm', use_noise=True, noise_amp=5, verbose=True, save_intermediate=True, save_intermediate_path='./results/generation')
/home/frank/.local/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/home/frank/tmp/single_video_generation/run_generation.py", line 70, in <module>
    VGPNN, orig_vid = vgpnn.get_vgpnn(
                      ^^^^^^^^^^^^^^^^
  File "/home/frank/tmp/single_video_generation/vgpnn.py", line 215, in get_vgpnn
    orig_vid = read_original_video(o.frames_dir, o.start_frame, o.end_frame, o.max_size, o.device, verbose=verbose, ext=ext)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/tmp/single_video_generation/utils/main_utils.py", line 48, in read_original_video
    frames = read_frames(frames_dir, start_frame, end_frame, resizer, device=device, verbose=verbose, ext=ext)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/tmp/single_video_generation/utils/main_utils.py", line 35, in read_frames
    x = frame_resizer(x)
        ^^^^^^^^^^^^^^^^
  File "/home/frank/tmp/single_video_generation/utils/resize_right.py", line 71, in resize
    field_of_view, weights = prepare_weights_and_field_of_view_1d(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/tmp/single_video_generation/utils/resize_right.py", line 165, in prepare_weights_and_field_of_view_1d
    field_of_view = get_field_of_view(projected_grid, cur_support_sz, in_sz,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/tmp/single_video_generation/utils/resize_right.py", line 284, in get_field_of_view
    field_of_view = mirror[fw.remainder(field_of_view, mirror.shape[0])]
                    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Comment by nivha** [comment]
Hi @Frank-Buss ,

I'm sorry but I no longer really maintains this repo. It seems like the problem you get is because the input is somehow on a different device, which may be due to some other tensors being initialized inside one of the functions without explicitlyl mentioning the device (something like torch.zeros / torch.ones etc.). So if your x is on a gpu and something is being initialized inside the function (where the default is to put it on cpu), then you would have such a problem.

So my guess is either make sure the input is on cpu and not gpu. or otherwise, find this troublesome initialized tensor and fix it to have the same device as the input (e.g., using torch.zeros_like / torch.ones_like etc.)

Cheers
